Декор каталога
htmlacademy-adaptive/1489759-cat-energy-22 pull request #13
Opened 2021-05-21 16:50 UTC by Dashulya1

2021-05-22 16:57 UTC, vovaborisenko requested changes
## не так уже все и страшно, но много чего нужно переделать

всегда при верстке думай как твою верстку могут сломать при изменении картинки, текста - тогда ты будешь верстать отличную универсальную верстку.

и принципы переиспользования по БЭМ ОЧЕНЬ важны и полезны для больших проектов.

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/table.scss
> +  border: collapse;
`border: collapse;` - невалидное выражение

наверно ты хотела использовать `border-collapse: collapse;` т.к. сейчас виден просвет между ячейками
![image](https://user-images.githubusercontent.com/30496847/119233560-6ad47700-bb32-11eb-8264-967c5bf2a82e.png)

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/button.scss
> +    }
у блока не может быть внешних отступов, при переиспользовании эти марджины у блока тебе боком выйдут

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/button.scss
> +  }
![image](https://user-images.githubusercontent.com/30496847/119233858-84c28980-bb33-11eb-9cc3-1396f634f9d6.png)
а вот здесь походу и вышли боком) теперь сложно выстроить все по флексам

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/button.scss
>    }
никаких внешних отступов у блока, даже если это модификатор

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/card.scss
>  }
это что за "красота"??!)
![image](https://user-images.githubusercontent.com/30496847/119233930-e1be3f80-bb33-11eb-8c41-9532324d9f28.png)

такой способ выравнивания текста ужасен. лучше используй симметричные отступы

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/catalog.scss
> +}
здесь лучше бы подошла сетка гридами.
т.к. лучше когда не пространство между товарами увеличивается, а карточка товара - увеличивается. (пустое пространство мало полезности несет, а карточка товара несет инфу)
![image](https://user-images.githubusercontent.com/30496847/119234075-a7a16d80-bb34-11eb-94dd-91677ebd4b1f.png)

при гридах такого не будет пустого места, все будет друг за другом
![image](https://user-images.githubusercontent.com/30496847/119234102-c99af000-bb34-11eb-97cc-c9de7c265cb5.png)

и все должно быть по макету в промежуточных ширинах экрана в мобиле один столбец, в планшете - 2, в десктопе 4
сейчас плохо выстроена сетка
![image](https://user-images.githubusercontent.com/30496847/119234158-06ff7d80-bb35-11eb-86c1-6eeeb67e7757.png)

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/catalog.scss
> +}
закладывать на чет\нечет в данном случае не оч идея)
![image](https://user-images.githubusercontent.com/30496847/119234213-5fcf1600-bb35-11eb-8224-a5c3a313b39e.png)

не всегда же картинки будут идти в таком порядке

нужно четко задать размеры элемента где должна быть фотка и внутри элемента расположить фотографию так как нужно.

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/add.scss
> +}
блок не должен знать о своем расположении, пололжении и порядке
для блока такие псевноселекторы недопустимы

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/add.scss
> +  }
![image](https://user-images.githubusercontent.com/30496847/119234381-48445d00-bb36-11eb-8988-96092fee5c1f.png)

по макету здесь линия в 1px

следует перенести эти линии на элементы `.catalog__add-item`, так ты избавишь от псевдоселектора у блока ( .add:last-child )

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/add.scss
> +  }
ну и здесь чего вдруг гриды, может сделаешь изначально гридами?

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/button.scss
> +}
`.button--show-all:not(:hover):active` - странный селектор, для чего он??

2021-05-22 16:57 UTC, vovaborisenko commented on source/sass/components/catalog.scss
> +}
`.catalog__card:nth-child(even) .card__link-img` постарайся избавиться от такого рода селекторов

2021-05-22 18:25 UTC, Dashulya1 commented on source/sass/components/button.scss
> +}
у меня кнопка просто красилась в зеленый если нажать на нее и свести курсор

2021-05-22 19:02 UTC, Dashulya1 commented on source/sass/components/catalog.scss
> +}
я избавилась, но картинки немного не по размеру,  пока так, а в следующем разделе тогда сделаю ретину

2021-05-23 07:37 UTC, vovaborisenko requested changes
#почти все сделано, молодец

в мобильной версии при расширении экрана вот такое происходит:
![image](https://user-images.githubusercontent.com/30496847/119252065-c47c8600-bbb2-11eb-9742-9048bb219959.png)

2021-05-23 07:37 UTC, vovaborisenko commented on source/sass/components/card.scss
> +  }
просто удали 43 строку `height: 206px;` и все будет ок

2021-05-26 20:21 UTC, merged