Разметка страницы с формой
htmlacademy-adaptive/1489759-cat-energy-22 pull request #3
Opened 2021-03-30 08:44 UTC by Dashulya1

2021-03-30 18:19 UTC, vovaborisenko commented on source/form.html
> +        </div>
здесь тоже нужно выделить повторяющиеся блоки

2021-03-31 05:22 UTC, Dashulya1 commented
Вроде сделала)

2021-03-31 18:37 UTC, vovaborisenko requested changes
# ХОРОШО!!!

одну штучку там подправь и все

2021-03-31 18:37 UTC, vovaborisenko commented on source/form.html
> +        </div>
`.data-field__icon-e-mail` и `.data-field__icon-tel` можно заменить на один класс. они же одинаковые, просто иконки разные.

2021-03-31 18:38 UTC, merged