Разметка страницы каталога
htmlacademy-adaptive/1489759-cat-energy-22 pull request #4
Opened 2021-04-02 04:54 UTC by Dashulya1

2021-04-02 18:21 UTC, vovaborisenko requested changes
# все нормально
есть замечания ниже

2021-04-02 18:21 UTC, vovaborisenko commented on source/catalog.html
> +        </div>
в 64 и 68 строке у тебя есть два одинаковых элемента (`.catalog__link`) 
не думаю, что им подойдут одинаковые свойства css.

если думаешь иначе объясни

2021-04-02 18:21 UTC, vovaborisenko commented on source/catalog.html
> +              </tr>
в 65 строке `.card-meta` не по БЭМ

2021-04-02 18:21 UTC, vovaborisenko commented on source/catalog.html
> +        </div>
видишь по названиям классам так и просится создать отдельный блок. значит нужно его создать

2021-04-02 18:21 UTC, vovaborisenko commented on source/catalog.html
> +            </table>
здесь таблица уже точно лишняя.
таблицы не позволяют себя стилизовать как ты захочешь, там есть нюансы.

замени просто на div

2021-04-02 18:21 UTC, vovaborisenko commented on source/catalog.html
> +          </div>
создай отдельный блок

2021-04-02 18:21 UTC, vovaborisenko commented on source/catalog.html
> +            </table>
для разнообразия можно здесь оставить таблицу. попрактикуешься немного с таблицами

но заголовок карточки вынеси из таблицы.

2021-04-02 18:21 UTC, vovaborisenko commented on source/catalog.html
> +        </div>
для семантичности каждую карточку сделай тегом article

2021-04-03 04:44 UTC, Dashulya1 commented on source/catalog.html
> +        </div>
лучше поменяю

2021-04-03 04:46 UTC, Dashulya1 commented on source/catalog.html
> +              </tr>
да, хорошо, правлю

2021-04-03 04:48 UTC, Dashulya1 commented on source/catalog.html
> +        </div>
хорошо, думала создать отдельный блок, но этот блок не повторялся, поэтому делать этого не стала

2021-04-03 05:21 UTC, Dashulya1 commented on source/catalog.html
> +          </div>
хорошо

2021-04-03 05:31 UTC, Dashulya1 commented on source/catalog.html
> +            </table>
да, хорошо, сделано

2021-04-03 05:34 UTC, Dashulya1 commented on source/catalog.html
> +        </div>
хорошо, будет сделано)

2021-04-05 05:46 UTC, vovaborisenko requested changes
# Отличная работа!!!

2021-04-05 05:46 UTC, vovaborisenko commented on source/catalog.html
>          <p class="address__city">Санкт-Петербург</p>
раз уж решила удалить модификатор `address__invite--text`, тогда класс ` address__invite-text` избыточен. удаляй его тоже

2021-04-05 05:46 UTC, merged