Стилизация главной страницы
htmlacademy-adaptive/1489759-cat-energy-22 pull request #5
Opened 2021-04-06 15:23 UTC by Dashulya1

2021-04-06 20:47 UTC, vovaborisenko requested changes
# Все идет как надо, молодец!!!
### очень важна база, так сказать фундамент
вот пару замечаний:

- добавлять всему контенту классы блока `page-text` не очень идея, т.к. обычного текста больше чем текста в заголовках. так что создай класс для заголовков и ему задай шрифт oswald. а html задай Arial.

- обычно в файле indent.scss пишут все начальные свойства проекта.
а в файле typography.scss подключают шрифты с помощью @font-face.

- не нужно разбивать свойства body и по файлам.

- и есть небольшое несоответствие
![image](https://user-images.githubusercontent.com/30496847/113775953-0e5bfa80-9732-11eb-812c-de370d50c0b4.png)

2021-04-06 20:47 UTC, vovaborisenko commented on source/index.html
>            </dl>
для чего тебе здесь модификатор `results__desc--text`??

2021-04-06 20:47 UTC, vovaborisenko commented on source/index.html
> +            <img class="slider__image slider__image--foreground" src="img/example-after.jpg" alt="Кот в хорошей форме">
все пути пиши лучше писать от корня, так же как при подключении css. так ты избежишь ошибок и лишней работы при перемещении файлов html

2021-04-06 20:47 UTC, vovaborisenko commented on source/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Oswald&display=swap&subset=cirillic,latin" rel="stylesheet">
в проекте есть файлы шрифтов их нужно подключить в файле scss.
подробнее https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/base/typography.scss
> +}
это вариант лучше:
.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  border: 0;
  padding: 0;
  white-space: nowrap;
  clip-path: inset(100%);
  clip: rect(0 0 0 0);
  overflow: hidden;
}

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/base/indent.scss
> +}
таким способом box-sizing ты задала только для body, т.к. box-sizing не наследуется
лучше
```
:root {
  box-sizing: border-box;
}

*, *::before, *::after {
  box-sizing: inherit;
}
```

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/base/indent.scss
> +}
для каждого блока должен быть свой файл scss

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/base/typography.scss
> +}
text-transform: uppercase; - лишнее т.к. у тебя же не весь текст в верхнем регистре

основным шрифтом сделай Arail  и размеры и цвет его здесь тоже задай

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/base/typography.scss
> +}
такие глобальные стили запрещены

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/base/typography.scss
> +}
это ты удалишь)

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/base/typography.scss
> +}
каждому блоку свой файл scss

font-weight: 40px; - невалидный код

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/components/address.scss
> +}
порядок css свойств нужно соблюдать
подробнее https://codeguide.academy/html-css.html#css-order

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/components/card-advantages.scss
> +}
у блока не может быть марджинов

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/components/card-example.scss
> +}
пути неправильно прописаны

и зачем картинкам задаешь background?

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/components/goals.scss
> +}
соблюдай порядок css свойств

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/components/main-nav.scss
> +}
у блока не может быть марджинов

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/components/promo.scss
> +}
у блока не может быть марджинов

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/components/promo.scss
> +}
пропиши путь относительно корня

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/components/slider.scss
> +}
соблюдай порядок свойоств

2021-04-06 20:47 UTC, vovaborisenko commented on source/sass/style.scss
> +@import "base/indent.scss";
все импорты с начальными настройками нужно вставлять в начале, чтобы их свойства могли перебить элементы компонентов без лишней специфичности

2021-04-08 11:22 UTC, Dashulya1 commented on source/index.html
>            </dl>
я как раз применила размер шрифта 12px, то небольшое несоответствие из-за него, но оно не сработало, заменила на обычный класс

2021-04-08 11:26 UTC, Dashulya1 commented on source/index.html
> +            <img class="slider__image slider__image--foreground" src="img/example-after.jpg" alt="Кот в хорошей форме">
да хорошо

2021-04-08 11:26 UTC, Dashulya1 commented on source/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Oswald&display=swap&subset=cirillic,latin" rel="stylesheet">
это сделала

2021-04-08 11:26 UTC, Dashulya1 commented on source/sass/base/typography.scss
> +}
окей

2021-04-08 11:26 UTC, Dashulya1 commented on source/sass/base/indent.scss
> +}
вставила, спасибо)

2021-04-08 11:30 UTC, Dashulya1 commented on source/sass/base/typography.scss
> +}
окей, убрала

2021-04-08 11:30 UTC, Dashulya1 commented on source/sass/base/typography.scss
> +}
обязательно, ахах

2021-04-08 11:33 UTC, Dashulya1 commented on source/sass/base/typography.scss
> +}
title у меня не блок, а класс для двух заголовков с одинаковым шрифтом, я его в base кину, можно?

2021-04-08 12:05 UTC, Dashulya1 commented on source/sass/components/address.scss
> +}
хорошо, постараюсь)

2021-04-08 12:26 UTC, Dashulya1 commented on source/sass/components/card-example.scss
> +}
решение просто нашла готовая по похожему слайдеру, я подробно его не смотрела, уберу пока просто

2021-04-08 12:28 UTC, Dashulya1 commented on source/sass/components/goals.scss
> +}
+ убрала маржин))

2021-04-08 12:32 UTC, Dashulya1 commented on source/sass/components/slider.scss
> +}
да, хорошо

2021-04-09 15:12 UTC, vovaborisenko requested changes
### очень хороший код!!!
прям аж душа радуется) молодец!!!

2021-04-09 15:12 UTC, vovaborisenko commented on source/index.html
> +    <link href="css/style.css" rel="stylesheet">
`<link href="css/style.css" rel="stylesheet">` - зачем здесь слэш вначале пути убрала?)

исправь на `<link href="/css/style.css" rel="stylesheet">`

2021-04-09 15:12 UTC, merged