Адаптивная сетка для главной страницы
htmlacademy-adaptive/1489759-cat-energy-22 pull request #8
Opened 2021-04-15 07:53 UTC by Dashulya1

2021-04-15 18:49 UTC, vovaborisenko requested changes
хорошо все,
только не забывай, что в БЭМ блоки не могут менять стили вложенных в них блоков.

каждый блок должен находится в отдельном файле - это упрощает поддержку кода.

2021-04-15 18:49 UTC, vovaborisenko commented on source/sass/abstracts/variables.scss
> +$desktop: 1288px;
размеры правильно определены. отлично!

2021-04-15 18:49 UTC, vovaborisenko commented on source/sass/components/button.scss
> +  }
кнопка на других страницах не имеет фиксированных размеров. фиксированные размеры нужно убрать
высоту лучше задать через min-height

2021-04-15 18:49 UTC, vovaborisenko commented on source/sass/components/promo.scss
> +}
селектор не по БЭМ
нужно создать модификатор для кнопки

2021-04-15 18:49 UTC, vovaborisenko commented on source/sass/components/results.scss
>  .desc-text {
`.desc-text` - это отдельный блок значит ему нужен отдельный файл

2021-04-15 18:49 UTC, vovaborisenko commented on source/sass/layout/footer.scss
> +}
каждому блоку нужен отдельный файл

2021-04-15 18:49 UTC, vovaborisenko commented on source/sass/layout/header.scss
> +}
каждому блоку нужен отдельный файл

2021-04-16 04:25 UTC, Dashulya1 commented on source/sass/components/button.scss
> +  }
да, хорошо

2021-04-16 16:13 UTC, vovaborisenko requested changes
перехвалил - теперь все очень плохо)

каждому блоку должен соответствовать ОДИН-Единственный файл стилей. вот как блок называется так и файл называется и он один на весь проект. еще вспомнил блоки не могут иметь свойство `order` (в итоге блок не должен знать о своем позиционировании ничего, его позиционирование задают элементы, в которых он будет находится).

представляешь как можно поддерживать проект когда для каждого блока в разных папках разные стили?! я уже запутался в файлах)

layout это что-то масштабное, как страница. не нужно туда пихать все сетки. это должна быть сетка для страницы и все. все остальное это компоненты.

2021-04-16 18:32 UTC, Dashulya1 commented
Надеюсь так)

2021-04-17 06:16 UTC, vovaborisenko requested changes
# Уже намного лучше,
но есть ошибочки)

---
## Для развития

вот есть полезный миксин для медиа запросов: (источник https://myrusakov.ru/10-useful-sass-mixins.html)
Миксин, который сохранит вам очень много времени! Вы можете использовать значения только в пикселях, но у нас есть также настройки контрольных точек по умолчанию, которые также работают, другие же – экономят время, сохраняя свои контрольные точки последовательно.
```
$breakpoints: (
  "phone":        400px,
  "phone-wide":   480px,
  "phablet":      560px,
  "tablet-small": 640px,
  "tablet":       768px,
  "tablet-wide":  1024px,
  "desktop":      1248px,
  "desktop-wide": 1440px
);
@mixin mq($width, $type: min) {
  @if map_has_key($breakpoints, $width) {
   $width: map_get($breakpoints, $width);
   @if $type == max {
    $width: $width - 1px;
   }
   @media only screen and (#{$type}-width: $width) {
    @content;
   }
  }
}
```
Пример ниже показывает увеличение внутренних отступов и размера шрифта, когда вьюпорт становится больше 1024px.
```
.site-header {
  padding: 2rem;
  font-size: 1.8rem;

  @include mq('tablet-wide') {
   padding-top: 4rem;
   font-size: 2.4rem;
  }
}
```

2021-04-17 06:16 UTC, vovaborisenko commented on source/sass/components/logo.scss
> +}
файл должен называться также как и блок. 
сейчас блок `logo-layout`, а файл - `logo`

2021-04-17 06:16 UTC, vovaborisenko commented on source/sass/components/main-nav.scss
>  }
в 11 строке лишняя обертка слелектором.
в итоге будет такое:
```
.main-nav__toggle {
  margin-left: auto;
  max-width: 24px;
}
@media (min-width: 768px) {
  .main-nav__toggle .main-nav__toggle { /* вложенность селекторов */
    display: none;
  }
}
```

2021-04-17 06:16 UTC, vovaborisenko commented on source/sass/components/promo.scss
> +
в 12 строке модификатор для `promo__intro`, в 36 строке сам элемент `promo__intro`.
модификаторы переопределяют или дополняют стили для элемента/блока. чтобы переопределение всегда без проблем сработало, нужно модификаторы писать после их элемента/блока.

2021-04-17 06:16 UTC, vovaborisenko commented on source/sass/components/socials.scss
> +}
для каждого блока нужен свой файл

2021-04-17 10:51 UTC, Dashulya1 commented on source/sass/components/main-nav.scss
>  }
да, подправлю

2021-04-17 10:52 UTC, Dashulya1 commented on source/sass/components/promo.scss
> +
точно, всегда забываю о порядке элементов)

2021-04-17 10:56 UTC, Dashulya1 commented on source/sass/components/socials.scss
> +}
хорошо

2021-04-17 11:34 UTC, Dashulya1 commented
Я пока не воспользовалась миксином, потому что не уверена, что сделаю это правильно) подразберусь только и попробую

2021-04-17 13:33 UTC, vovaborisenko commented
теперь все хорошо!)

2021-04-17 13:33 UTC, merged